# Generated by Django 5.1.3 on 2024-11-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaldoaluno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
