# Generated by Django 5.1.3 on 2024-11-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaldoaluno', '0002_usuario_delete_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=500, unique=True),
        ),
    ]
