# Generated by Django 5.1.3 on 2024-12-08 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='agente_si',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_atribuidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='grupo',
            field=models.CharField(blank=True, choices=[(None, 'Nenhum'), ('SI', 'Segurança da Informação')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Em Tratamento', 'Em Tratamento'), ('Fechado', 'Fechado')], default='Aberto', max_length=20),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='denunciante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
